export const creditPackages = [
  {
    id: "starter",
    name: "",
    credits: 100,
    price: 20,
    originalPrice: 20,
    discount: 0,
    description: "",
    popular: false,
  },
  {
    id: "basic",
    name: "",
    credits: 200,
    price: 40,
    originalPrice: 40,
    discount: 0,
    description: "",
    popular: false,
  },
  {
    id: "standard",
    name: "",
    credits: 375,
    price: 75,
    originalPrice: 85,
    discount: 12,
    description: "",
    popular: false,
  },
  {
    id: "premium",
    name: "",
    credits: 500,
    price: 100,
    originalPrice: 125,
    discount: 20,
    description: "",
    popular: false,
  },
  {
    id: "pro",
    name: "",
    credits: 750,
    price: 150,
    originalPrice: 200,
    discount: 25,
    description: "",
    popular: false,
  },
  {
    id: "enterprise",
    name: "",
    credits: 1000,
    price: 200,
    originalPrice: 300,
    discount: 33,
    description: "",
    popular: false,
  },
]
