export const creditPackages = [
  {
    id: "starter",
    name: "Quick Start",
    credits: 100,
    price: 20,
    originalPrice: 20,
    discount: 0,
    description: "Perfect for a single introductory session",
    popular: false,
  },
  {
    id: "basic",
    name: "Session Builder",
    credits: 200,
    price: 40,
    originalPrice: 40,
    discount: 0,
    description: "Ideal for occasional mentorship sessions",
    popular: false,
  },
  {
    id: "standard",
    name: "Growth Accelerator",
    credits: 375,
    price: 75,
    originalPrice: 85,
    discount: 12,
    description: "Great value for consistent learning and growth",
    popular: false,
  },
  {
    id: "premium",
    name: "Expert Connect",
    credits: 500,
    price: 100,
    originalPrice: 125,
    discount: 20,
    description: "Most popular for in-depth expert guidance",
    popular: true,
  },
  {
    id: "pro",
    name: "Mastery Path",
    credits: 750,
    price: 150,
    originalPrice: 200,
    discount: 25,
    description: "For dedicated learners seeking comprehensive development",
    popular: false,
  },
  {
    id: "enterprise",
    name: "Enterprise Solution",
    credits: 1000,
    price: 200,
    originalPrice: 300,
    discount: 33,
    description: "Ultimate package for extensive, long-term mentorship",
    popular: false,
  },
]
